- name: edxapp 水平扩展
  hosts: all
  become: True
  gather_facts: True
  vars:
    EDXAPP_LMS_NGINX_PORT: '80'
    NGINX_SET_X_FORWARDED_HEADERS: True
    EDXAPP_LMS_BASE: "{{ EDXAPP_LMS_SITE_NAME }}:{{ EDXAPP_LMS_NGINX_PORT }}"
    EDXAPP_CMS_BASE: "{{ EDXAPP_CMS_SITE_NAME }}:{{ EDXAPP_CMS_NGINX_PORT }}"
    EDXAPP_DEFAULT_FILE_STORAGE:  "django.core.files.storage.FileSystemStorage"  # edxapp 水平扩展，文件上传如何处理？
    EDXAPP_MONGO_HOSTS: '{{ master_host }}'
    EDXAPP_MYSQL_HOST: '{{ master_host }}'
    EDXAPP_MEMCACHE: [ '{{ master_host }}:11211' ]
    EDXAPP_RABBIT_HOSTNAME: '{{ master_host }}'
    EDXAPP_CELERY_BROKER_TRANSPORT: 'amqp'
    EDXAPP_PLATFORM_NAME: 'Your Platform Name Here'
    CREATE_SERVICE_WORKER_USERS: False
    EDXAPP_REINDEX_ALL_COURSES: False
    EDXAPP_CLEARSESSIONS_CRON_ENABLED: False
    migrate_db: False
  roles:
   - role: nginx
     nginx_sites:
     - lms
     - cms
     nginx_default_sites: "{{ EDXAPP_NGINX_DEFAULT_SITES }}"
     nginx_extra_sites: "{{ NGINX_EDXAPP_EXTRA_SITES }}"
     nginx_extra_configs: "{{ NGINX_EDXAPP_EXTRA_CONFIGS }}"
     nginx_redirects: "{{ NGINX_EDXAPP_CUSTOM_REDIRECTS }}"
     nginx_skip_enable_sites: "{{ EDXAPP_NGINX_SKIP_ENABLE_SITES }}"
   - edxapp

