- name: edxapp 水平扩展
  hosts: all
  become: True
  gather_facts: True
  vars:
    EDXAPP_MONGO_HOSTS: '{{ master_host }}'
    EDXAPP_MYSQL_HOST: '{{ master_host }}'
    EDXAPP_MEMCACHE: [ '{{ master_host }}:11211' ]
    EDXAPP_RABBIT_HOSTNAME: '{{ master_host }}'
    EDXAPP_CELERY_BROKER_TRANSPORT: 'amqp'
    EDXAPP_PLATFORM_NAME: 'Your Platform Name Here'
    CREATE_SERVICE_WORKER_USERS: False
    EDXAPP_REINDEX_ALL_COURSES: False
    EDXAPP_CLEARSESSIONS_CRON_ENABLED: False
    migrate_db: False
    edxapp_cms_gunicorn_port: 8010
    edxapp_cms_gunicorn_host: 0.0.0.0
    edxapp_lms_gunicorn_port: 8000
    edxapp_lms_gunicorn_host: 0.0.0.0
  roles:
   - edxapp

